### ISSUE TITLE
Feature Request - Support using ProjectID or Slug

### ISSUE THREAD

**Issue by cjm721** [Wyn-Price/CurseMaven-OLD#3]
Been adding a lot of mods to do some larger scale testing in my development environment (some weird multi-mod conflicts). To add them all is a bit tedious as have to copy and paste every Slug+FileId. 

If ProjectID was supported I could do the following to speed up my adding.

Twitch Launcher exports ProjectID+FileId for its ModPacks can just take that file and turn it into a projectId->fileId pairs which are then easy to make into a list of curse.resolve(x,y) using a bit of multi-cursor.

**Comment by Wyn-Price** [comment]
So instead of `curse.resolve("jei", "2724420")` it would be `curse.resolveID("238222", "2724420")` ? That sounds like it's easily doable, although it would mean it takes an extra http request (if your internet is slow it might take a little bit longer). 

If you could, can you provide an example of the format that the Twitch Launcher exports in, so I can make it so you can just put it in directly. Without having to reformat.

Sorry for taking a while to respond, for some reason notifications for this repo have been turned off.

**Comment by cjm721** [comment]
[Example from Adventrues of Halk](https://gist.github.com/cjm721/847512139d7d156a087e9d4a136a799e)

Its the files array inside the top level json object.

**Comment by Wyn-Price** [comment]
Ah okay. You'd have to do some regex or replacing to get it to work, but would something like `curse.resolveID(238222, 2724420)` be good?

**Comment by cjm721** [comment]
Yep that works for me.

**Comment by Wyn-Price** [comment]
Fixed in 1.2.0
