### ISSUE TITLE
Cache in the wrong place

### ISSUE THREAD

**Issue by GoryMoon** [Wyn-Price/CurseMaven-OLD#4]
CurseMaven: 1.1.0
Gradle: 2.14

Currently, the cache is placed in `$GRADLE_HOME\caches` instead of the `.gradle\caches` like all other caches.
As an example it places it in 
`C:\Users\Gustaf\.gradle\wrapper\dists\gradle-2.14-bin\76oc0mnc3ieqtsukq90mp0rxk\gradle-2.14\caches\curse_gradle` instead of `C:\Users\Gustaf\.gradle\caches\curse_gradle` where the user expects it to be placed.
Took some digging before I could find the cache to purge it as it wasn't in the normal position.

**Comment by Wyn-Price** [comment]
I'm away on holiday in North Wales for the next week, but if someone is able to, they could fix this.
All they would need to do is change [this](https://github.com/Wyn-Price/CurseMaven/blob/0f210113dec6940b1f94451c2f05ec5101ed793a/src/main/groovy/com/wynprice/cursemaven/repo/CurseMavenRepo.groovy#L35) to use Gradle User Home rather than Gradle Home.
